pluginPrefix: '&7[&6ChatSystem&7]&f'
news: 'Neuigkeiten dieses Servers :)'
newsPeriodMinutes: 5
defaultColors:
  - '&f'
  - '&6'
allowedColors:
  - '&c'
  - '&4'
blacklist:
  - 'Wort1'
  - 'Wort2'
  - 'Wort3'
replace:
  - '***'
  - 'Lieb'
  - 'Test'